apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connect-config
data:
  CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
  CONNECT_BOOTSTRAP_SERVERS: kafka-0.kafka-headless:29092
  CONNECT_GROUP_ID: post-connect
  CONNECT_CONFIG_STORAGE_TOPIC: _post-configs
  CONNECT_OFFSET_STORAGE_TOPIC: _post-offsets
  CONNECT_STATUS_STORAGE_TOPIC: _post-status
  CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
  CONNECT_REPLICATION_FACTOR: "1"
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"