apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  CLUSTER_ID: 'q1Sh-9_ISia_zwGINzRvyQ'
  KAFKA_NODE_ID: "1"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
  KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-0.kafka-headless:29092,PLAINTEXT_HOST://localhost:9092'
  KAFKA_LISTENERS: 'PLAINTEXT://kafka-0.kafka-headless:29092,CONTROLLER://kafka-0.kafka-headless:29093,PLAINTEXT_HOST://0.0.0.0:9092'
  KAFKA_PROCESS_ROLES: 'broker,controller'
  KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-0.kafka-headless:29093'
  KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
  KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"